# Generated by Django 4.2.16 on 2024-11-28 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0019_alter_postview_options_postinteraction_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinteraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_post_interactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
