# Generated by Django 4.2.16 on 2024-12-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_useraccount_role_useraccount_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='otp_secret',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
